@hostname = http://localhost:8000

# Register User Name
#
# Sample Response:
# {
#   "success": true,
#   "data": {
#     "token": "4|MqPPHpfaB88uYmEovqInNr2WQLzCJe7aovRDZSE3a6cf249f",
#     "name": "John5"
#   },
#   "message": "User register successfully."
# }
#
POST {{hostname}}/api/register HTTP/1.1
Content-Type: multipart/form-data; boundary=DummyFormData

--DummyFormData
Content-Disposition: form-data; name="name"

John5
--DummyFormData
Content-Disposition: form-data; name="email"

some4@email.com
--DummyFormData
Content-Disposition: form-data; name="password"

aaaa2
--DummyFormData
Content-Disposition: form-data; name="c_password"

aaaa2
--DummyFormData--

###

# Login User
# Sample Success:
# {
#   "success": true,
#   "data": {
#     "token": "6|qGh47kFkMHsqjS0mMZ2rXsqy4iEAOt1OhNYjMycv02d60b46",
#     "name": "John2"
#   },
#   "message": "User login successfully."
# }
#
# Sample Failure:
# {
#   "success": false,
#   "message": "Unauthorised.",
#   "data": {
#     "error": "Unauthorised"
#   }
# }
POST {{hostname}}/api/login
Content-Type: multipart/form-data; boundary=DummyFormData

--DummyFormData
Content-Disposition: form-data; name="email"

some4@email.com
--DummyFormData
Content-Disposition: form-data; name="password"

aaaa2
--DummyFormData--
###

# Test not implemented
GET {{hostname}}/api/products

###

# Test not implemented
POST {{hostname}}/api/products

###

# Test not implemented
GET {{hostname}}/api/products/1

###

# Test not implemented
DELETE {{hostname}}/api/products/1
